printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
trailingComma: all
bracketSpacing: true
endOfLine: lf
proseWrap: preserve
htmlWhitespaceSensitivity: css
overrides:
  - files: '*.html'
    options:
      printWidth: 120
